---
roles:
  # Install a role from Ansible Galaxy.
  #- name: geerlingguy.adminer
  #  version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.mysql
    version: 2.1.1
    source: https://galaxy.ansible.com

Avoir la meme version de mysql-serveur sur les deux serveurs de bases de donnees
Installer ubuntu-server 2024
Telecharger le containeur webjava
Avoir le pare-feu Fortinet 7.2
Installer ubuntu_desktop_guest 2023
